media:
  input: public
  output: /public
content:
  - name: "movies"
    type: "collection"
    label: "Movies"
    path: "src/content/movie"
    subfolders: false
    format: yaml-frontmatter
    view:
      fields:
        [
          name,
          releaseDate,
          categoryRatings.gore,
          categoryRatings.creepy,
          categoryRatings.jumpscares,
          categoryRatings.suspense,
          categoryRatings.psychological,
        ]
      primary: name
      sort: [releaseDate]
      default:
        sort: releaseDate
        order: desc
      search: [mame]
    fields:
      - { name: "name", label: "Movie Name", type: "string", required: true }
      - { name: "tmdbId", label: "TMDB ID", type: "string", required: true }
      - { name: "tmdbPosterId", label: "TMDB Poster ID", type: "string", required: true, pattern: { message: 'This must be a valid TMDB poster id (e.g. hello@example.com).', regex: "\/[a-zA-Z0-9]{10,}\\.jpg" } }
      - { name: "releaseDate", label: "Release Date", type: "date", required: true }
      - name: "categoryRatings"
        label: "Category Ratings"
        type: "object"
        fields:
          - {
              name: "gore",
              label: "Gore",
              type: "number",
              default: 0,
              required: true,
              options: { min: 0, max: 10 },
            }
          - {
              name: "creepy",
              label: "Creepy",
              type: "number",
              default: 0,
              required: true,
              options: { min: 0, max: 10 },
            }
          - {
              name: "jumpscares",
              label: "Jumpscares",
              type: "number",
              default: 0,
              required: true,
              options: { min: 0, max: 10 },
            }
          - {
              name: "suspense",
              label: "Suspense",
              type: "number",
              default: 0,
              required: true,
              options: { min: 0, max: 10 },
            }
          - {
              name: "psychological",
              label: "Psychological",
              type: "number",
              default: 0,
              required: true,
              options: { min: 0, max: 10 },
            }
      - { name: "body", label: "Description", type: "rich-text" }
