name: Auto PR from movie-updates to dev

on:
  push:
    branches:
      - movie-updates

jobs:
  create-pr:
    permissions: 
      pull-requests: write 
    runs-on: ubuntu-latest
    steps:
      - name: create pull request
        run: gh pr create -B dev -H movie-updates --title 'Merge movie-updates into dev' --body 'Auto PR by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}