name: Auto PR from movie-updates to dev

on:
  push:
    branches:
      - movie-updates

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create or update PR
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: dev
          head: movie-updates
          title: "Auto-merge: Updates from movie-updates"
          body: "This PR was automatically created to merge changes from movie-updates into dev."
          branch: auto-pr-movie-updates
          labels: auto-merge
          auto-merge: true

      - name: Skip if PR exists
        if: steps.create_pr.outputs.pull-request-operation == 'none'
        run: echo "PR already exists. Skipping."
