name: Auto PR from dev to main

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    permissions: 
      pull-requests: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: dev
      - name: Create pull request
        run: gh pr create -B main -H dev --title 'Merge dev into main' --body 'Auto PR by Github action' || gh pr edit dev --title 'Merge dev into main' --body 'Auto PR by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Enable auto-merge
        run: gh pr merge dev --auto --merge
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}