name: Auto PR from movie-updates to dev

on:
  push:
    branches:
      - movie-updates

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: movie-updates

      - name: Create or update PR
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Updates from movie-updates"
          branch: movie-updates-to-dev
          base: dev
          delete-branch: true
          team-reviewers: editors
          body: "This PR was automatically created to merge changes from movie-updates into dev."