name: Bulk Movie Generator

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate-movies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.RELEASES_APP_ID }}
          private-key: ${{ secrets.RELEASES_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: dev

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run bulk movie generator
        env:
          TMDB_BEARER_TOKEN: ${{ secrets.TMDB_BEARER_TOKEN }}
        run: |
          cd scripts
          python bulkMovieMDGenerator.py \
            --start-date "$(date -d '6 months ago' +%Y-%m-%d)" \
            --end-date "$(date -d '12 months' +%Y-%m-%d)" \
            --min-popularity 5
            
      - name: Check for new files
        id: check_changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Capture only newly added files (not modified ones)
          new_files=$(git ls-files --others --exclude-standard src/content/movie)

          if [ -n "$new_files" ]; then
            echo "no_changes=false" >> $GITHUB_ENV
            git add src/content/movie
            git commit -m "Add new movie markdown files"
          else
            echo "no_changes=true" >> $GITHUB_ENV
          fi

      - name: Push changes to dev
        if: env.no_changes == 'false'
        run: |
          git push origin dev