name: Bulk Movie Generator

on:
  schedule:
    - cron: "0 0 * * 0" # Runs weekly on Sunday at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  generate-movies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r scripts/requirements.txt

      - name: Run bulk movie generator
        env:
          TMDB_BEARER_TOKEN: ${{ secrets.TMDB_BEARER_TOKEN }}
        run: |
          cd scripts
          python bulkMovieMDGenerator.py \
            --start-date "$(date -d '6 months ago' +%Y-%m-%d)" \
            --end-date "$(date -d '12 months' +%Y-%m-%d)" \
            --min-popularity 10

      - name: Check for changes
        id: check_changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add src/content/movie
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_ENV
          else
            echo "no_changes=false" >> $GITHUB_ENV
            git commit -m "Add new movie markdown files"
          fi

      - name: Push changes and create PR
        if: env.no_changes == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          branch: bulk-movie-generator
          base: dev
          title: "Add new movie markdown files"
          body: "This PR adds new movie markdown files generated by the bulk movie generator script."
