name: Deploy CDK
on:
  push:
    branches: [ main, "deploy-setup" ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Run Build
      run: npm run build
    - name: Run deploy
      run: npm run cdk-deploy