name: Deploy CDK
on:
  push:
    branches: [ main ]
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy:
    permissions:
      # Default permissions
      contents: write
      packages: read

      deployments: write
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.RELEASES_APP_ID }}
        private-key: ${{ secrets.RELEASES_APP_PRIVATE_KEY }}
    - uses: chrnorm/deployment-action@v2
      name: Create GitHub deployment
      id: deployment
      with:
        token: ${{ steps.app-token.outputs.token }}
        environment-url: http://scarescale.com
        environment: production

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ steps.app-token.outputs.token }}

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: |
        npm ci
        npm --prefix infrastructure install

    - name: setup git config
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Run release
      run: npm run release --ci
      env:
        token: ${{ steps.app-token.outputs.token }}

    - name: Run Build
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@master
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: "eu-west-1"

    - name: Run deploy
      run: npm run cdk-deploy

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ steps.app-token.outputs.token }}
        environment-url: ${{ steps.deployment.outputs.environment_url }}
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
        state: 'success'

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ steps.app-token.outputs.token }}
        environment-url: ${{ steps.deployment.outputs.environment_url }}
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
        state: 'failure'