name: Deploy GitHub Pages
on:
  push:
    branches:
      - dev
  workflow_run:
    workflows: ["Tests"]
    branches: [dev]
    types: 
      - completed
    conclusion: success
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
  deploy:
    permissions:
      contents: read
      packages: read

      deployments: write
      pages: write
      id-token: write
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.RELEASES_APP_ID }}
        private-key: ${{ secrets.RELEASES_APP_PRIVATE_KEY }}

    - uses: chrnorm/deployment-action@v2
      name: Create GitHub deployment
      id: deployment
      with:
        token: ${{ steps.app-token.outputs.token }}
        environment: dev

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ steps.app-token.outputs.token }}

    - name: Install, build, and upload your site output
      uses: withastro/action@v4

    - name: Deploy to GitHub Pages
      id: pages-deployment
      uses: actions/deploy-pages@v4

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ steps.app-token.outputs.token }}
        environment-url: ${{ steps.deployment.outputs.environment_url }}
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
        state: 'success'

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ steps.app-token.outputs.token }}
        environment-url: ${{ steps.deployment.outputs.environment_url }}
        deployment-id: ${{ steps.deployment.outputs.deployment_id }}
        state: 'failure'