name: Static Code Analysis
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx,.astro