name: Static Code Analysis
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npm run eslint --ext .js,.jsx,.ts,.tsx,.astro --output-file eslint_report.json --format json src
    - name: Annotate Code Linting Results
      uses: ataylorme/eslint-annotate-action@1.0.4
      if: always()
      with:
        repo-token: '${{ secrets.GITHUB_TOKEN ***REMOVED******REMOVED***'
        report-json: 'eslint_report.json'
